### PR TITLE
Small improvements

### PR DESCRIPTION
**Pull request by v1ne**
Disassembling some firmware on a SN8F2288, I did the following changes to successfully disassemble it and compare it with the re-assembly in SN8 C Studio and against a patched object file disassembled by gds.exe to ensure that dissn8 generates the right disassembly.

What do you think?

### CODE REVIEW

**Comment by vpelletier** [comment]
How did you identify the missing B0MOV instructions ? FWIW, I originally generated an asm file with the 256 possible instructions as .dw entries,then launched the debugger and checked how each would be decoded. Some (like these) would not be decoded, so I left them asides (although there is indeed a clear pattern here).

About odd sizes, then I would prefer the check to be simplified to `if len(instruction) != 2:`, as `read` always returns a string and boolean evaluation is just `len(instruction) == 0 `, which is redundant with the proper `!= 2` check.

About discarding the header, all good to me.

About adding the bootloader entry, I would prefer to keep this file just with what the cpu implements, rather than how the SDK builds code for it. FWIW, when disassembling I have a separate configuration file with the in-progress disassembly (naming functions, memory offsets, adding comments), and load both: `dissn8 --chip sn8f2288.cfg --chip analysis.cfg <...>` .

**Comment by v1ne** [comment]
Thank you for the helpful and descriptive comments!
I changed the PR as follows:
* B0MOV: I encountered the issue fixed by 7999d61c3bf87a899b62f4ecf81c811e57b732a3 and modelled `B0MOV` after similar instructions and during rebasing, the additions for `X`, `L` and `R` were left. But they are actually invalid, as I just tested it with SN8 C Studio: It won't accept `B0MOV X, #0x23` etc. whereas `B0MOV Y, #0x23` is valid. I dropped that commit. Sorry for the noise!
* odd sizes: Changed as suggested.
* Bootloader entry: Commit removed since it's better to use a second cfg file as overlay for a specific project.

**Comment by vpelletier** [comment]
All good to me, thanks for contributing !

Going further about `B0MOV` variants, another interesting thing would be to know how the hardware executes these, beyond what the assembler accepts. But this will likely take some carefully controlled environment to check (if they do not behave exactly as predicted), and the only such microcontroller I have is in the keyboard I use to type these lines... Not sure I want to brick it yet :) .

**Comment by v1ne** [comment]
@vpelletier: Thank you!

What a coincidence! My project was about fixing a bug in a certain USB keyboard of a popular former three-letter brand. That's also the only SN8 controller that I have and I also can't afford to brick it, but I had to modify the firmware update tool to upload my changed firmware.

**Comment by vpelletier** [comment]
It seems to be the most widespread implementation of that microcontroller - or at least the one which falls most often in tinkering hands :) .

I must say I never completed my goal though, which was to get the trackpoint to *not* send scroll events, as xorg can generate these from middle-click + x & y moves and the keyboard was somehow still emitting a middleclick event, causing unexpected clipboard pasting. It seems xorg has a workaround for this since then, as scrolling works as expected...

**Comment by Marisa-Chan** [comment]
You also can check correct opcode disassembly by compare result with my disassembler for sn8 chips https://github.com/Marisa-Chan/sn8dis/tree/master/sn8tools

**Pull request merged**
